### ISSUE TITLE
Analytics for GHA chart instructions

### ISSUE THREAD

**Issue by ThatcherK** [devinit/gha-data-visualisations#72]
Would be good also to know if users are opening the instructions (that's recorded for other charts)
Also spotted on the current analytics we have events for "Recipient chart" and "Recipients chart" if they are the same, can we combine? Thanks!

**Comment by edwinmp** [comment]
@davidebukali please confirm whether we've done this already.

**Comment by davidebukali** [comment]
@edwinmp seems we do not have events for opening map instructions, should be similar implementation as other charts; I could not find events for "Recipient chart".

**Comment by edwinmp** [comment]
Is it possible to implement this in an open way, so that adding new charts won't require analytics updates for the chart instructions? I'm sure we should be able to capture the chart title and using that to identify the target chart for the instruction accordion.

**Comment by wakibi** [comment]
@davidebukali @ThatcherK as discussed, let's implement this in the most obvious way, and create another task / discussion to investigate Edwin's suggestion.
